Feature/kdg 55 order overview
elision-stages/stage-KDG-FE pull request #23
Opened 2022-05-19 13:43 UTC by vanbabe

2022-05-19 14:03 UTC, antonv-elision requested changes

2022-05-19 14:03 UTC, antonv-elision commented on marketplace/src/app/components/table/table.component.html
> +         currentPageReportTemplate="Showing {first} to {last} of {totalRecords} products"
"Showing {first} to {last} of {totalRecords} products"
This isn't a valid template text for every table

2022-05-19 14:03 UTC, antonv-elision commented on marketplace/src/app/components/table/table.component.html
> +            <input pInputText type="text" (input)="filter(dt2, $event)" placeholder="Search nameword" class="w-full"/>
wtf is a nameword

2022-05-19 14:03 UTC, antonv-elision commented on marketplace/src/app/components/table/table.component.html
> +      <td>
This TD should have a condition for when no actions are present at all

2022-05-19 14:03 UTC, antonv-elision commented on marketplace/src/app/components/table/table.component.html
> +                   [text]="filterKeyword ? 'No products have been found for ' + filterKeyword : 'No products found'"></p-message>
These texts are dependent on the table contents and are not always products

2022-05-19 14:03 UTC, antonv-elision commented on marketplace/src/app/views/user/shared/order-overview/order-overview.component.html
> +             [cols]="columns" [idColumn]="'orderNumber'"
Can't you simply do idColumn="orderNumber" instead of [idColumn]="'orderNumber'" ?

2022-05-20 07:31 UTC, vanbabe commented on marketplace/src/app/components/table/table.component.html
> +            <input pInputText type="text" (input)="filter(dt2, $event)" placeholder="Search nameword" class="w-full"/>
haha replaced all 'key' with 'name'

2022-05-20 07:49 UTC, merged