Feature/kdg 8 api
elision-stages/stage-KDG-FE pull request #4
Opened 2022-04-29 09:44 UTC by antonv-elision

2022-04-29 14:21 UTC, BrentEerlingen commented on marketplace/src/app/components/login/login.component.ts
>    ngOnInit(): void {
Remove empty OnOnit method

2022-04-29 14:26 UTC, BrentEerlingen commented on marketplace/src/app/components/login/login.component.ts
> +    console.log(this.loginForm)
Remove console logs

2022-04-29 14:28 UTC, BrentEerlingen commented on marketplace/src/app/components/login/login.component.ts
> +  onLogin(): void {
This method has no logic, only displaying messages or logs. Remove this method if it will not be added to the PR

2022-04-29 14:29 UTC, BrentEerlingen requested changes
Please resolve all comments before it can be merged in

2022-04-29 14:46 UTC, antonv-elision commented
@BrentEerlingen ready for merge

2022-05-02 06:34 UTC, schrogl requested changes

2022-05-02 06:34 UTC, schrogl commented on marketplace/src/app/components/login/login.component.ts
> +  onLogin(): void {
if this is in another pr remove the method here

2022-05-04 20:39 UTC, vanbabe approved these changes

2022-05-04 20:40 UTC, merged